#
###################################
# Site wide configuration
####################################
#
title: GranRookey
email: granrookey@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: https://granrookey.github.io # the base hostname & protocol for your site
keywords: ["Programming", "Machine Learning", "Android"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: GranRookey
  avatar: yj_profile.png
  job: "Data Scientist"
  bio: "A Newbie from Tourism & Marketing management."
  email: granrookey@gmail.com
  disqus-shortname: yjblog
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: renyuanz #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
